<?php
/**
 *  * Created by PhpStorm.
 * User: x3RABBITx3
 * Date: 07.02.2019
 * Time: 15:44
 */

namespace app\modules\v1\classes;

use Yii;
use yii\base\InlineAction;
use yii\filters\AccessControl;
use yii\filters\auth\HttpBearerAuth;
use yii\rest\ActiveController;
use WebSocket\Client;
use yii\web\HttpException;

class ActiveControllerExtended extends ActiveController
{
    protected $wssUrl = 'ws://127.0.0.1:6001';
    protected $transaction;

    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['authenticator'] = [
            'class' => HttpBearerAuth::className(),
            'optional' => ['options', 'bootstrap', 'login']
        ];

        $behaviors['access'] = [
            'class' => AccessControl::className(),
            'rules' => [
                [
                    'actions' => ['options'],
                    'allow' => true,
                ],
                [
                    'actions' => [$this->action->id],
                    'allow' => true,
                ]
            ]
        ];
        return $behaviors;
    }

    /**
     * @param $action InlineAction
     * @return bool
     * @throws \yii\web\BadRequestHttpException
     * @throws HttpException
     */
    public function beforeAction($action)
    {
//        СНАЧАЛА ВЫЗВАТЬ РОДИТЕЛЬСКИЙ BEFORE ACTION, ИНАЧЕ АУТЕНТИФИКАЦИЯ НЕ ПРОЙДЕТ И РЕЗУЛЬТАТОМ ПРОВЕРКИ ПРАВ БУДЕТ ЧУЩШЬ!!!
        if (!parent::beforeAction($action)) {
            return false;
        }
        Yii::$container->set('yii\data\Pagination', ['pageSizeLimit' => 1000, 'pageSize' => 1000]);
        Yii::$app->response->headers->set('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept, Cookie, Authorization');
        Yii::$app->response->headers->set('Access-Control-Allow-Credentials', 'true');
        Yii::$app->response->headers->set('Access-Control-Allow-Origin', '*');

        $ddddddddddddd = $this->action;
        $ffffffffd = $ddddddddddddd->getUniqueId();
        $permission = Yii::$app->getRequest()->getMethod() . ' /' . $ffffffffd;
        if (!Yii::$app->getUser()->can($permission) && $this->action->id !== 'options') {
            throw new HttpException(499);
        }

        return true; // TODO: Change the autogenerated stub
    }

    public function afterAction($action, $result)
    {

        return parent::afterAction($action, $result);
    }

    public function runAction($id, $params = [])
    {
        $this->transaction = Yii::$app->db->beginTransaction();
        try {
            $time = microtime(true);
            $result = parent::runAction($id, $params); // TODO: Change the autogenerated stub
            $this->transaction->commit();
            $timeEnd = microtime(true);
            $timeDiff = $timeEnd - $time;

            if (!empty(Yii::$app->app->cmdTables)) {
                $wsc = new Client($this->wssUrl);
                $wsc->send(json_encode(Yii::$app->app->cmdTables));
            }
            return $result;
        } catch (\Exception $e) {
            $this->transaction->rollBack();
            //throw new \Exception('Transaction rolled back. ' . $e->getMessage());
            throw $e;

        }
    }
}
