#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

// comment out the following two lines when deployed to production
if (in_array(gethostname(), ['tsrz-apc', 'apc', 'dell-apc', 'DESKTOP-7Q5VD89'])) {
    defined('YII_DEBUG') or define('YII_DEBUG', true);
    defined('YII_ENV') or define('YII_ENV', 'dev');
    //xdebug_disable();
}

define('CURRENT_API_URL', 'https://api.textileadmin.ru');
//define('CURRENT_API_URL', 'http://api.textileadmin.loc');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/config/console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
