<?php

namespace app\modules\v1;

class V1Mod extends \yii\base\Module
{
	public $layout = false;

	function init()
	{
		parent::init(); // TODO: Change the autogenerated stub
		\Yii::$app->user->enableSession = false;
	}
}